const checkoutStyles = document.createElement('link'); checkoutStyles.rel = 'stylesheet'; checkoutStyles.href = 'css/checkout/checkout-note.css?v=20260925-cachefix1'; document.head.append(checkoutStyles);
const cartKey = 'ivbags-cart';
const apiBase = window.IVBAGS_API_URL || (location.hostname === 'localhost' || location.protocol === 'file:' ? 'http://localhost:8787/api' : '/api');
function loadWompiWidget() { return new Promise((resolve, reject) => { if (window.WidgetCheckout) return resolve(); const script = document.createElement('script'); script.src = 'https://checkout.wompi.co/widget.js'; script.onload = resolve; script.onerror = () => reject(new Error('No se pudo cargar el widget de Wompi.')); document.head.append(script); }); }
let cart = JSON.parse(localStorage.getItem(cartKey) || '[]');
const money = (value) => `$${Number(value).toLocaleString('es-CO')}`;
const total = () => cart.reduce((sum, item) => sum + (item.price * item.quantity), 0);
const checkoutTotal = () => total() + (typeof deliveryData === 'function' ? deliveryData().shippingFee : 0);
const fakePayButton = document.createElement('button'); fakePayButton.className = 'fake-purchase-button'; fakePayButton.id = 'fakePayButton'; fakePayButton.type = 'button'; fakePayButton.textContent = 'Compra ficticia ↗'; document.querySelector('#payButton')?.after(fakePayButton);
const shippingZone = document.querySelector('.checkout-zone');
const shippingHeading = shippingZone?.querySelector('.zone-heading');
if (shippingHeading && !document.querySelector('#shippingOptions')) { shippingHeading.insertAdjacentHTML('beforeend', '<button class="delivery-info-button" id="deliveryInfoButton" type="button">ver tarifas y tiempos</button>'); shippingHeading.insertAdjacentHTML('afterend', '<div class="shipping-options" id="shippingOptions"><p class="field-kicker">elige cómo quieres recibir tu pedido</p><label class="shipping-option active"><input type="radio" name="shippingType" value="udea" checked><span><strong>Entrega en la UdeA</strong><small>Martes y jueves · el asesor coordina contigo</small></span></label><label class="shipping-option"><input type="radio" name="shippingType" value="metro"><span><strong>Domicilio Medellín / área metropolitana</strong><small>Medellín $12.000 · Bello, Envigado, Itagüí y Sabaneta $14.000</small></span></label><label class="shipping-option"><input type="radio" name="shippingType" value="national"><span><strong>Envío nacional</strong><small>Entrega a cualquier ciudad de Colombia · $16.000</small></span></label></div><div class="udea-note" id="udeaNote">Tu entrega será en la UdeA. El asesor se contactará contigo para coordinar el punto y el día, martes o jueves.</div>'); const formGrid = shippingZone.querySelector('.form-grid'); formGrid?.insertAdjacentHTML('beforeend', '<label id="buildingField">Edificio o unidad<input id="customerBuilding" placeholder="Edificio, unidad residencial, torre"></label><label class="wide" id="notesField">Notas para el mensajero<textarea id="deliveryNotes" rows="3" placeholder="Portería, apartamento, indicaciones especiales..."></textarea></label>'); }
function selectedShipping() { return document.querySelector('input[name="shippingType"]:checked')?.value || 'udea'; }
function deliveryData() { const type = selectedShipping(); const city = type === 'udea' ? 'UdeA' : document.querySelector('#customerCity').value.trim(); const normalizedCity = city.toLocaleLowerCase('es-CO'); const fee = type === 'udea' ? 0 : type === 'national' ? 16000 : normalizedCity.includes('medellín') || normalizedCity.includes('medellin') ? 12000 : 14000; return { type, label: type === 'udea' ? 'Entrega en la UdeA' : type === 'metro' ? (fee === 12000 ? 'Domicilio Medellín' : 'Área metropolitana') : 'Envío nacional', shippingFee: fee, name: document.querySelector('#customerName').value.trim(), email: document.querySelector('#customerEmail').value.trim(), address: type === 'udea' ? 'Entrega coordinada en la UdeA' : document.querySelector('#customerAddress').value.trim(), city, building: type === 'udea' ? '' : document.querySelector('#customerBuilding')?.value.trim() || '', notes: type === 'udea' ? 'El asesor coordinará la entrega los martes o jueves.' : document.querySelector('#deliveryNotes')?.value.trim() || '', phone: document.querySelector('#customerPhone').value.trim() }; }
function setupShipping() { const fields = document.querySelector('.checkout-zone .form-grid'); const address = document.querySelector('#customerAddress')?.closest('label'); const city = document.querySelector('#customerCity')?.closest('label'); const building = document.querySelector('#buildingField'); const notes = document.querySelector('#notesField'); const note = document.querySelector('#udeaNote'); document.querySelectorAll('input[name="shippingType"]').forEach((input) => input.addEventListener('change', () => { const isUdea = input.value === 'udea' && input.checked; if (!input.checked) return; document.querySelectorAll('.shipping-option').forEach((option) => option.classList.toggle('active', option.querySelector('input') === input)); [address, city, building, notes].forEach((field) => { if (field) field.hidden = isUdea; }); [address, city, building, notes].forEach((field) => field?.querySelector('input, textarea')?.toggleAttribute('required', !isUdea)); if (note) note.hidden = !isUdea; })); document.querySelector('#deliveryInfoButton')?.addEventListener('click', () => { const modal = document.createElement('div'); modal.className = 'delivery-info-modal'; modal.innerHTML = '<div class="delivery-info-card"><button type="button" aria-label="Cerrar">×</button><span class="delivery-paper-tab">Envíos</span><p>Los envíos se hacen desde Medellín, a todo Colombia.</p><h3>Área metropolitana</h3><p>Medellín, Bello, Envigado, Itagüí y Sabaneta tienen entrega con tarifa según la zona.</p><h3>Entregas UdeA</h3><p>Los martes y jueves hacemos entregas gratuitas dentro de la universidad.</p><h3>Nacionales</h3><p>Disponibles para todo el país, con tarifa según destino.</p><h3>Tiempos de entrega</h3><p>Las piezas listas se despachan al día siguiente de la compra. Los pedidos personalizados pueden tardar hasta 15 días hábiles.</p></div>'; document.body.append(modal); modal.querySelector('button').onclick = () => modal.remove(); modal.onclick = (event) => { if (event.target === modal) modal.remove(); }; }); document.querySelector('input[name="shippingType"][value="udea"]')?.dispatchEvent(new Event('change', { bubbles: true })); }
setupShipping();
document.querySelectorAll('input[name="shippingType"], #customerCity').forEach((field) => field.addEventListener('change', renderCart));
document.querySelector('#customerCity')?.addEventListener('input', renderCart);
function renderCart() {
  document.querySelector('#cartCount').textContent = `${cart.length} ${cart.length === 1 ? 'pieza' : 'piezas'}`;
  document.querySelector('#summaryTotal').textContent = money(checkoutTotal());
  document.querySelector('#payTotal').textContent = money(checkoutTotal());
  document.querySelector('#cartItems').innerHTML = cart.length ? cart.map((item, index) => `<div class="cart-item"><div class="cart-item-preview">${item.image ? `<img src="${item.image}" alt="Diseño de ${item.name}"/>` : '✦'}</div><div class="cart-item-info"><strong>${item.name}</strong><small>${item.text || 'pieza pintada a mano'}<br/>cantidad: ${item.quantity}</small></div><div><span class="cart-item-price">${money(item.price * item.quantity)}</span><button class="remove-item" data-remove="${index}" aria-label="Quitar ${item.name}">×</button></div></div>`).join('') : '<p class="empty-cart">Tu carrito está esperando una pieza especial.</p>';
  document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => { cart.splice(Number(button.dataset.remove), 1); localStorage.setItem(cartKey, JSON.stringify(cart)); renderCart(); }));
}
async function validateCartStock() { const response = await fetch('/api/products'); const products = await response.json().catch(() => []); if (!response.ok || !Array.isArray(products)) throw new Error('No pudimos verificar el stock. Inténtalo de nuevo.'); const requested = new Map(); cart.forEach((item) => { if (item.productId) requested.set(Number(item.productId), (requested.get(Number(item.productId)) || 0) + Number(item.quantity || 1)); }); for (const [productId, quantity] of requested) { const product = products.find((entry) => Number(entry.id) === productId); if (!product || Number(product.stock) < quantity) throw new Error(`No hay stock suficiente de ${product?.name || 'este producto'}. Disponible: ${product?.stock || 0}.`); } }
renderCart();
document.querySelectorAll('.payment-option').forEach((button) => button.addEventListener('click', () => { document.querySelector('.payment-option.active')?.classList.remove('active'); button.classList.add('active'); document.querySelector('#cardFields').hidden = button.dataset.payment !== 'card'; }));
document.querySelector('#payButton').addEventListener('click', async () => {
  const customer = JSON.parse(localStorage.getItem('ivbags-customer') || 'null');
  if (!customer) { alert('Inicia sesión antes de realizar la compra.'); window.location.href = 'index.html'; return; }
  const required = ['customerName', 'customerEmail', 'customerPhone'];
  const delivery = deliveryData();
  const shippingRequired = selectedShipping() === 'udea' ? true : Boolean(delivery.address && delivery.city && delivery.building && delivery.notes);
  const valid = required.every((id) => document.querySelector(`#${id}`).value.trim()) && shippingRequired;
  if (!cart.length) { alert('Añade una pieza al carrito antes de pagar.'); return; }
  if (!valid) { const missing = required.find((id) => !document.querySelector(`#${id}`).value.trim()) || (selectedShipping() === 'udea' ? 'customerName' : ['customerAddress', 'customerCity', 'customerBuilding', 'deliveryNotes'].find((id) => !document.querySelector(`#${id}`)?.value.trim())); document.querySelector(`#${missing}`)?.focus(); alert('Completa todos los datos de entrega.'); return; }
  try { await validateCartStock(); } catch (error) { alert(error.message); return; }
  const number = `#IV-${Math.floor(1000 + Math.random() * 8999)}`;
  const payButton = document.querySelector('#payButton');
  payButton.disabled = true;
  const readJson = async (response) => { const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `La API respondió con ${response.status}.`); return body; };
  fetch(`${apiBase}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${customer.token}` }, body: JSON.stringify({ items: cart, delivery, design: cart.map((item) => ({ ...item })) }) }).then(readJson).then((order) => fetch(`${apiBase}/wompi/signature`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${customer.token}` }, body: JSON.stringify({ reference: order.reference, amount: order.total }) })).then(readJson).then(async (payment) => { await loadWompiWidget(); if (!payment.publicKey || !payment.signature) throw new Error('Wompi no está configurado todavía en Cloudflare.'); const widget = new WidgetCheckout({ currency: payment.currency, amountInCents: payment.amountInCents, reference: payment.reference, publicKey: payment.publicKey, signature: { integrity: payment.signature }, redirectUrl: `${location.origin}/checkout.html` }); widget.open((result) => { if (result?.transaction?.status === 'APPROVED') completeOrder(result.transaction.id); }); }).catch((error) => { alert(error.message || 'No se pudo iniciar el pago.'); payButton.disabled = false; });
  return;
  function completeOrder(transactionId) {
  const orders = JSON.parse(localStorage.getItem('ivbags-orders') || '[]');
  orders.push({ number, customer, delivery: deliveryData(), items: cart, total: total(), status: 'Pagado', createdAt: new Date().toISOString() });
  localStorage.setItem('ivbags-orders', JSON.stringify(orders));
  document.querySelector('#orderNumber').textContent = number;
  document.querySelector('#confirmation').hidden = false;
  localStorage.removeItem(cartKey);
  cart = [];
  }
});

document.querySelector('#fakePayButton')?.addEventListener('click', async () => {
  const customer = JSON.parse(localStorage.getItem('ivbags-customer') || 'null');
  if (!customer) { alert('Inicia sesión antes de realizar la compra ficticia.'); window.location.href = 'index.html'; return; }
  if (!cart.length) { alert('Añade una pieza al carrito antes de comprar.'); return; }
  const delivery = deliveryData();
  if (!delivery.name || !delivery.email || !delivery.phone || (delivery.type !== 'udea' && (!delivery.address || !delivery.city || !delivery.building || !delivery.notes))) { alert('Completa los datos de entrega.'); return; }
  const button = document.querySelector('#fakePayButton'); button.disabled = true;
  try { await validateCartStock(); const response = await fetch(`${apiBase}/orders`, { method: 'POST', headers: { 'Content-Type': 'application/json', ...(customer?.token ? { Authorization: `Bearer ${customer.token}` } : {}) }, body: JSON.stringify({ demo: true, items: cart, delivery, design: cart.map((item) => ({ ...item })) }) }); const order = await response.json(); if (!response.ok) throw new Error(order.error || 'No se pudo crear el pedido ficticio.'); document.querySelector('#orderNumber').textContent = `#${order.reference}`; document.querySelector('#confirmation').hidden = false; localStorage.removeItem(cartKey); cart = []; renderCart(); } catch (error) { alert(error.message); } finally { button.disabled = false; }
});
