const sessionKey = 'ivbags-admin-session';
const stateKey = 'ivbags-admin-state';
const usersKey = 'ivbags-admin-users';
const defaultState = { statuses: { 'IV-2048': 'Pagado', 'IV-2047': 'En producción', 'IV-2046': 'Enviado', 'IV-2045': 'Pagado' }, sales: 4, revenue: 2845000, stock: 37 };
const state = JSON.parse(localStorage.getItem(stateKey) || JSON.stringify(defaultState));
const users = JSON.parse(localStorage.getItem(usersKey) || JSON.stringify([{ name: 'Propietario', username: 'admin' }]));
const loginScreen = document.querySelector('#loginScreen');
const adminApp = document.querySelector('#adminApp');
const saveState = () => localStorage.setItem(stateKey, JSON.stringify(state));
const showApp = () => { loginScreen.hidden = true; adminApp.hidden = false; const activeUser = sessionStorage.getItem('ivbags-admin-user') || 'admin'; const owner = users.find((user) => user.username === activeUser)?.name || 'Propietario'; const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT); while (walker.nextNode()) walker.currentNode.nodeValue = walker.currentNode.nodeValue.replaceAll('Ivanna', owner); initializeDashboard(); };
if (sessionStorage.getItem(sessionKey) === 'ok') showApp();

document.querySelector('#loginForm')?.addEventListener('submit', (event) => { event.preventDefault(); const username = document.querySelector('#loginUser').value.trim(); const password = document.querySelector('#loginPassword').value; const valid = users.some((user) => user.username === username && user.password === password) || (username === 'admin' && password === 'ivtotebags'); if (valid) { sessionStorage.setItem(sessionKey, 'ok'); sessionStorage.setItem('ivbags-admin-user', username); showApp(); } else document.querySelector('#loginError').classList.add('visible'); });
document.querySelector('#logoutButton')?.addEventListener('click', () => { sessionStorage.removeItem(sessionKey); window.location.reload(); });

function openModal(id) { const modal = document.querySelector(`#${id}`); modal?.classList.add('open'); modal?.setAttribute('aria-hidden', 'false'); }
function closeModal(button) { const modal = button.closest('.admin-modal'); modal?.classList.remove('open'); modal?.setAttribute('aria-hidden', 'true'); }
function addModal(id, content) { if (document.querySelector(`#${id}`)) return; const modal = document.createElement('div'); modal.id = id; modal.className = 'admin-modal'; modal.setAttribute('aria-hidden', 'true'); modal.innerHTML = `<div class="modal-card">${content}</div>`; document.body.append(modal); modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.querySelector('[data-close-panel]')); }); modal.querySelector('[data-close-panel]').addEventListener('click', () => closeModal(modal.querySelector('[data-close-panel]'))); }
function injectControls() {
  const sidebar = document.querySelector('.admin-nav');
  const toggle = document.createElement('button'); toggle.className = 'sidebar-toggle'; toggle.textContent = '☰'; toggle.setAttribute('aria-label', 'Contraer menú'); toggle.addEventListener('click', () => document.body.classList.toggle('sidebar-collapsed')); document.querySelector('.admin-sidebar').prepend(toggle);
  const adminLink = document.createElement('a'); adminLink.href = '#administradores'; adminLink.innerHTML = '◎ <span>Administradores</span>'; sidebar.append(adminLink);
  const tools = document.createElement('div'); tools.className = 'admin-tools'; tools.innerHTML = '<button class="admin-danger" id="deleteSalesButton">Eliminar ventas</button><button class="panel-link" id="manageAdminsButton">Gestionar accesos</button>'; document.querySelector('.sales-panel .panel-heading').append(tools);
  const adminZone = document.createElement('section'); adminZone.id = 'administradores'; adminZone.className = 'admin-panel'; adminZone.innerHTML = `<div class="panel-heading"><div><p class="admin-kicker">accesos privados</p><h2>Administradores</h2></div><button class="admin-primary" id="addAdminButton">+ Crear administrador</button></div><div class="manager-list" id="managerList"></div>`; document.querySelector('.admin-main').append(adminZone); renderUsers();
  document.querySelector('#deleteSalesButton').addEventListener('click', () => openModal('deleteSalesPanel')); document.querySelector('#manageAdminsButton').addEventListener('click', () => document.querySelector('#administradores').scrollIntoView({ behavior: 'smooth' })); document.querySelector('#addAdminButton').addEventListener('click', () => openModal('adminPanel'));
}
function renderUsers() { document.querySelector('#managerList').innerHTML = users.map((user) => `<div><span>${user.name}</span><small>${user.username}</small></div>`).join(''); }
function initializeDashboard() { if (document.body.dataset.ready) return; document.body.dataset.ready = 'true'; injectControls(); setupExistingModals(); loadCustomerOrders(); setupSales(); setupProduction(); setupInventory(); updateStats(); setupAdminViews(); }
function loadCustomerOrders() { const orders = JSON.parse(localStorage.getItem('ivbags-orders') || '[]'); const table = document.querySelector('.sales-table'); orders.slice(-8).forEach((order) => { const item = order.items[0] || {}; const row = document.createElement('div'); row.className = 'sales-row sale-row'; row.dataset.order = order.number.replace('#',''); row.innerHTML = `<span class="order-code">${order.number}</span><span>${order.delivery.name}</span><span>${item.name || 'Pieza personalizada'}</span><strong>$${Number(order.total).toLocaleString('es-CO')}</strong><select class="status-select" data-order-status="${row.dataset.order}"><option selected>${order.status}</option><option>En producción</option><option>Enviado</option><option>Entregado</option></select><button class="row-action" data-order-detail="${row.dataset.order}">ver ↗</button>`; table.append(row); }); }
document.addEventListener('click', (event) => { const button = event.target.closest('[data-order-detail]'); if (!button) return; const order = JSON.parse(localStorage.getItem('ivbags-orders') || '[]').find((item) => item.number.replace('#','') === button.dataset.orderDetail); const design = order?.items?.[0]; if (design?.image) document.querySelector('#detailPreview').src = design.image; if (design?.text) document.querySelector('#detailPreviewText').textContent = design.text; });
function setupAdminViews() { const links = [...document.querySelectorAll('.admin-nav a')]; const sections = [...document.querySelectorAll('.admin-main > section')]; const show = (id) => sections.forEach((section) => { section.hidden = id !== 'resumen' && section.id !== id; }); links.forEach((link) => link.addEventListener('click', (event) => { const id = link.getAttribute('href')?.slice(1); if (!id) return; event.preventDefault(); links.forEach((item) => item.classList.remove('active')); link.classList.add('active'); show(id); window.scrollTo({ top: 0, behavior: 'smooth' }); })); show('resumen'); }
function setupExistingModals() { document.querySelectorAll('[data-open-panel]').forEach((button) => button.addEventListener('click', () => openModal(button.dataset.openPanel))); document.querySelectorAll('[data-close-panel]').forEach((button) => button.addEventListener('click', () => closeModal(button))); document.querySelectorAll('.admin-modal').forEach((modal) => modal.addEventListener('click', (event) => { if (event.target === modal) closeModal(modal.querySelector('[data-close-panel]')); })); document.querySelector('#productForm')?.addEventListener('submit', addProduct); document.querySelector('#categoryForm')?.addEventListener('submit', addCategory); document.querySelectorAll('[data-category-color]').forEach((button) => button.addEventListener('click', () => { document.querySelector('[data-category-color].selected')?.classList.remove('selected'); button.classList.add('selected'); })); }
function setupSales() { document.querySelectorAll('[data-order-status]').forEach((select) => { const order = select.dataset.orderStatus; select.value = state.statuses[order] || select.value; select.dataset.value = select.value; select.addEventListener('change', () => { state.statuses[order] = select.value; saveState(); }); }); document.querySelectorAll('[data-order-detail]').forEach((button) => button.addEventListener('click', () => { const row = button.closest('.sale-row'); const order = button.dataset.orderDetail; document.querySelector('#detailTitle').textContent = `#${order}`; document.querySelector('#detailClient').textContent = row.children[1].textContent; document.querySelector('#detailProduct').textContent = row.children[2].textContent; document.querySelector('#detailStatus').value = state.statuses[order] || 'Pagado'; document.querySelector('#detailPreviewText').textContent = order === 'IV-2047' ? 'días bonitos' : row.children[2].textContent; addDownloadButton(); openModal('orderPanel'); })); document.querySelector('#saveOrderStatus')?.addEventListener('click', () => { const order = document.querySelector('#detailTitle').textContent.replace('#',''); const value = document.querySelector('#detailStatus').value; state.statuses[order] = value; saveState(); document.querySelector(`[data-order-status="${order}"]`).value = value; closeModal(document.querySelector('#orderPanel [data-close-panel]')); }); }
function addDownloadButton() { if (document.querySelector('#downloadDesign')) return; const button = document.createElement('button'); button.id = 'downloadDesign'; button.className = 'panel-link'; button.textContent = 'Descargar diseño ↓'; button.addEventListener('click', () => { const link = document.createElement('a'); link.href = document.querySelector('#detailPreview').src; link.download = `${document.querySelector('#detailTitle').textContent.replace('#','')}-diseño.png`; link.click(); }); document.querySelector('.customer-design').prepend(button); }
function setupProduction() { document.querySelectorAll('.production-column article').forEach((card) => card.addEventListener('dragstart', () => card.classList.add('dragging'))); document.querySelectorAll('.production-column').forEach((column) => { column.addEventListener('dragover', (event) => { event.preventDefault(); column.classList.add('drag-over'); }); column.addEventListener('dragleave', () => column.classList.remove('drag-over')); column.addEventListener('drop', (event) => { event.preventDefault(); const card = document.querySelector('.dragging'); column.classList.remove('drag-over'); if (!card) return; column.append(card); card.classList.remove('dragging'); const small = card.querySelector('small'); if (small) small.textContent = column.dataset.production === 'Listo' ? 'listo para empacar' : column.dataset.production === 'En proceso' ? 'en producción' : 'pendiente de iniciar'; }); }); }
function addProduct(event) { event.preventDefault(); const data = new FormData(event.currentTarget); const card = document.createElement('article'); card.className = 'admin-product'; card.innerHTML = `<div class="admin-product-art art-yellow">✦</div><div class="admin-product-info"><strong>${data.get('name')}</strong><span>${data.get('category')} · ${data.get('price')}</span><b>${data.get('availability')}</b><div class="product-actions"><input class="stock-field" type="number" min="0" value="1" aria-label="Stock inicial"/><button class="sell-product" type="button">Vender</button></div></div>`; document.querySelector('.add-product-card').before(card); state.stock += 1; saveState(); updateStats(); event.currentTarget.reset(); closeModal(event.currentTarget.closest('.admin-modal').querySelector('[data-close-panel]')); bindSell(card); }
function bindSell(card) { card.querySelector('.sell-product')?.addEventListener('click', () => { const stock = card.querySelector('.stock-field'); if (Number(stock.value) > 0) { stock.value = Number(stock.value) - 1; state.sales += 1; state.revenue += 145000; state.stock = Math.max(0, state.stock - 1); saveState(); updateStats(); } }); }
function setupInventory() { document.querySelectorAll('.admin-product:not(.add-product-card)').forEach((card) => { if (!card.querySelector('.product-actions')) { card.querySelector('.admin-product-info').insertAdjacentHTML('beforeend', '<div class="product-actions"><input class="stock-field" type="number" min="0" value="1" aria-label="Stock inicial"/><button class="sell-product" type="button">Vender</button></div>'); bindSell(card); } }); }
function updateStats() { const revenue = document.querySelector('#revenueStat'); const orders = document.querySelector('#ordersStat'); const stock = document.querySelector('#stockStat'); if (revenue) revenue.textContent = `$${state.revenue.toLocaleString('es-CO')}`; if (orders) orders.textContent = state.sales; if (stock) stock.textContent = state.stock; }

addModal('deleteSalesPanel', '<button class="modal-close" data-close-panel>×</button><p class="admin-kicker">acción irreversible</p><h2>Eliminar ventas</h2><p class="confirm-copy">Se eliminarán todos los registros de ventas guardados en este panel. <strong>Necesitas confirmar tu contraseña.</strong></p><form id="deleteSalesForm"><label>Contraseña<input id="deletePassword" type="password" required placeholder="••••••••"/></label><p class="login-error" id="deleteError">Contraseña incorrecta.</p><button class="admin-danger" type="submit">Eliminar todos los registros</button></form>');
addModal('adminPanel', '<button class="modal-close" data-close-panel>×</button><p class="admin-kicker">accesos privados</p><h2>Crear administrador</h2><form id="newAdminForm"><label>Nombre<input name="name" required placeholder="Nombre de la persona"/></label><label>Usuario<input name="username" required placeholder="usuario"/></label><label>Contraseña<input name="password" type="password" minlength="6" required placeholder="mínimo 6 caracteres"/></label><button class="admin-primary" type="submit">Guardar administrador ↗</button></form>');
document.querySelector('#deleteSalesForm')?.addEventListener('submit', (event) => { event.preventDefault(); const password = document.querySelector('#deletePassword').value; if (password !== 'ivtotebags') { document.querySelector('#deleteError').classList.add('visible'); return; } document.querySelectorAll('.sale-row').forEach((row) => row.remove()); state.sales = 0; state.revenue = 0; saveState(); updateStats(); closeModal(event.currentTarget.closest('.admin-modal').querySelector('[data-close-panel]')); });
document.querySelector('#newAdminForm')?.addEventListener('submit', (event) => { event.preventDefault(); const data = new FormData(event.currentTarget); users.push({ name: data.get('name'), username: data.get('username'), password: data.get('password') }); localStorage.setItem(usersKey, JSON.stringify(users)); renderUsers(); event.currentTarget.reset(); closeModal(event.currentTarget.closest('.admin-modal').querySelector('[data-close-panel]')); });
