const customerKey = 'ivbags-customer';
const apiBase = window.IVBAGS_API_URL || (location.hostname === 'localhost' || location.protocol === 'file:' ? 'http://localhost:8787/api' : 'https://ivbags-api.onrender.com/api');
const getCustomer = () => JSON.parse(localStorage.getItem(customerKey) || 'null');
const saveCustomer = (customer) => localStorage.setItem(customerKey, JSON.stringify(customer));
function closeCustomerAuth(modal) { modal.classList.remove('open'); modal.style.opacity = '0'; modal.style.pointerEvents = 'none'; }
async function api(path, options = {}) { const response = await fetch(`${apiBase}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'No se pudo completar la solicitud'); return body; }
function customerModal() {
  if (document.querySelector('#customerAuth')) return document.querySelector('#customerAuth');
  const modal = document.createElement('div'); modal.id = 'customerAuth'; modal.className = 'customer-auth';
  modal.innerHTML = `<div class="customer-auth-card"><button class="customer-auth-close" aria-label="Cerrar">×</button><p class="page-kicker">tu espacio iv bags</p><h2>Guarda tus ideas,<br/><em>llévalas contigo.</em></h2><div class="auth-tabs"><button class="active" data-auth-tab="login">Iniciar sesión</button><button data-auth-tab="register">Crear cuenta</button></div><form id="customerAuthForm"><label id="fullNameField" hidden>Nombre<input id="customerFullName" placeholder="Tu nombre"/></label><label>Correo electrónico<input id="customerEmail" type="email" required placeholder="hola@ejemplo.com"/></label><label>WhatsApp<input id="customerPhone" placeholder="300 000 0000"/></label><label>Contraseña<input id="customerPassword" type="password" minlength="8" required placeholder="mínimo 8 caracteres"/></label><label id="verificationField" hidden>Código recibido por correo<input id="verificationCode" inputmode="numeric" maxlength="6" placeholder="000000"/></label><button class="page-action" type="submit" id="customerAuthSubmit">Entrar a mi espacio ↗</button><button class="resend-code" type="button" id="resendCode" hidden>Solicitar otro código</button><p class="customer-auth-message" id="customerAuthMessage"></p></form><small>Antes de producir tu pieza te contactaremos al WhatsApp registrado.</small></div></div>`;
  document.body.append(modal); let mode = 'login'; let verificationEmail = '';
  const setMode = (nextMode) => { mode = nextMode; modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authTab === mode)); modal.querySelector('#fullNameField').hidden = mode !== 'register'; modal.querySelector('#verificationField').hidden = true; modal.querySelector('#resendCode').hidden = true; modal.querySelector('#customerAuthSubmit').textContent = mode === 'register' ? 'Crear cuenta y enviar código ↗' : 'Entrar a mi espacio ↗'; modal.querySelector('#customerAuthMessage').textContent = ''; };
  modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.addEventListener('click', () => setMode(tab.dataset.authTab))); modal.querySelector('.customer-auth-close').addEventListener('click', () => closeCustomerAuth(modal)); modal.addEventListener('click', (event) => { if (event.target === modal) closeCustomerAuth(modal); }); setMode('login');
  modal.querySelector('#customerAuthForm').addEventListener('submit', async (event) => { event.preventDefault(); const message = modal.querySelector('#customerAuthMessage'); const submit = modal.querySelector('#customerAuthSubmit'); submit.disabled = true; message.textContent = 'Conectando con iv bags…'; try { const email = modal.querySelector('#customerEmail').value.trim().toLowerCase(); const password = modal.querySelector('#customerPassword').value; if (mode === 'register' && !modal.querySelector('#verificationField').hidden) { const result = await api('/auth/verify', { method: 'POST', body: JSON.stringify({ email: verificationEmail, code: modal.querySelector('#verificationCode').value.trim() }) }); saveCustomer({ ...result.user, token: result.token, verified: true }); closeCustomerAuth(modal); updateCustomerUI(); return; } if (mode === 'register') { const result = await api('/auth/register', { method: 'POST', body: JSON.stringify({ name: modal.querySelector('#customerFullName').value.trim(), email, password, phone: modal.querySelector('#customerPhone').value.trim() }) }); verificationEmail = email; modal.querySelector('#verificationField').hidden = false; modal.querySelector('#resendCode').hidden = false; modal.querySelector('#customerAuthSubmit').textContent = 'Confirmar correo ↗'; message.textContent = result.message; return; } const result = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) }); saveCustomer({ ...result.user, token: result.token, verified: true }); closeCustomerAuth(modal); updateCustomerUI(); } catch (error) { message.textContent = error.message; } finally { submit.disabled = false; } });
  modal.querySelector('#resendCode').addEventListener('click', () => { modal.querySelector('#verificationField').hidden = true; modal.querySelector('#customerAuthSubmit').textContent = 'Crear cuenta y enviar código ↗'; modal.querySelector('#customerAuthMessage').textContent = 'Vuelve a enviar el formulario para solicitar un nuevo código.'; }); return modal;
}
function openCustomerAuth() { const modal = customerModal(); modal.classList.add('open'); modal.style.opacity = '1'; modal.style.pointerEvents = 'auto'; }
function updateCustomerUI() { const customer = getCustomer(); document.querySelectorAll('[data-customer-name]').forEach((node) => { node.textContent = customer ? customer.name : 'Iniciar sesión'; }); document.querySelectorAll('[data-customer-action]').forEach((node) => node.onclick = customer ? () => { localStorage.removeItem(customerKey); updateCustomerUI(); } : openCustomerAuth); }
function addGlobalCart() { if (document.querySelector('.global-cart-button')) return; const button = document.createElement('a'); button.className = 'global-cart-button'; button.href = 'checkout.html'; button.innerHTML = 'carrito <b id="globalCartCount">0</b>'; document.body.append(button); const update = () => { const count = JSON.parse(localStorage.getItem('ivbags-cart') || '[]').reduce((sum, item) => sum + (item.quantity || 1), 0); button.querySelector('b').textContent = count; }; update(); window.addEventListener('storage', update); }
document.addEventListener('DOMContentLoaded', () => { customerModal(); updateCustomerUI(); addGlobalCart(); });
