const customerKey = 'ivbags-customer';
const pendingKey = 'ivbags-pending-verification';
const getCustomer = () => JSON.parse(localStorage.getItem(customerKey) || 'null');
const saveCustomer = (customer) => localStorage.setItem(customerKey, JSON.stringify(customer));
function closeCustomerAuth(modal) { modal.classList.remove('open'); modal.style.opacity = '0'; modal.style.pointerEvents = 'none'; }
function customerModal() {
  if (document.querySelector('#customerAuth')) return document.querySelector('#customerAuth');
  const modal = document.createElement('div'); modal.id = 'customerAuth'; modal.className = 'customer-auth';
  modal.innerHTML = `<div class="customer-auth-card"><button class="customer-auth-close" aria-label="Cerrar">×</button><p class="page-kicker">tu espacio iv bags</p><h2>Guarda tus ideas,<br/><em>llévalas contigo.</em></h2><div class="auth-tabs"><button class="active" data-auth-tab="login">Iniciar sesión</button><button data-auth-tab="register">Crear cuenta</button></div><form id="customerAuthForm"><label id="fullNameField" hidden>Nombre<input id="customerFullName" placeholder="Tu nombre"/></label><label>Correo electrónico<input id="customerEmail" type="email" required placeholder="hola@ejemplo.com"/></label><label>Contraseña<input id="customerPassword" type="password" minlength="6" required placeholder="mínimo 6 caracteres"/></label><label id="verificationField" hidden>Código de verificación<input id="verificationCode" inputmode="numeric" maxlength="6" placeholder="000000"/></label><button class="page-action" type="submit" id="customerAuthSubmit">Entrar a mi espacio ↗</button><button class="resend-code" type="button" id="resendCode" hidden>Reenviar código</button><p class="customer-auth-message" id="customerAuthMessage"></p></form><small>Te escribiremos al WhatsApp que registres antes de pintar tu pieza.</small></div></div>`;
  document.body.append(modal); let mode = 'login';
  const setMode = (nextMode) => { mode = nextMode; const registering = mode === 'register'; modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authTab === mode)); modal.querySelector('#fullNameField').hidden = !registering; modal.querySelector('#verificationField').hidden = true; modal.querySelector('#resendCode').hidden = true; modal.querySelector('#customerAuthSubmit').textContent = registering ? 'Crear cuenta y verificar ↗' : 'Entrar a mi espacio ↗'; modal.querySelector('#customerAuthMessage').textContent = ''; };
  modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.addEventListener('click', () => setMode(tab.dataset.authTab))); modal.querySelector('.customer-auth-close').addEventListener('click', () => closeCustomerAuth(modal)); modal.addEventListener('click', (event) => { if (event.target === modal) closeCustomerAuth(modal); }); setMode('login');
  modal.querySelector('#customerAuthForm').addEventListener('submit', (event) => { event.preventDefault(); const email = modal.querySelector('#customerEmail').value.trim().toLowerCase(); const password = modal.querySelector('#customerPassword').value; const name = modal.querySelector('#customerFullName').value.trim() || email.split('@')[0]; const stored = JSON.parse(localStorage.getItem(`ivbags-user-${email}`) || 'null'); const verification = modal.querySelector('#verificationField'); if (mode === 'register' && !verification.hidden) { const pending = JSON.parse(localStorage.getItem(pendingKey) || 'null'); if (pending?.email === email && pending.code === modal.querySelector('#verificationCode').value.trim()) { localStorage.setItem(`ivbags-user-${email}`, JSON.stringify({ name: pending.name, email, password: pending.password, verified: true })); saveCustomer({ name: pending.name, email, verified: true }); localStorage.removeItem(pendingKey); closeCustomerAuth(modal); updateCustomerUI(); } else modal.querySelector('#customerAuthMessage').textContent = 'El código no coincide. Revisa tu correo.'; return; } if (mode === 'register') { const code = String(Math.floor(100000 + Math.random() * 900000)); localStorage.setItem(pendingKey, JSON.stringify({ name, email, password, code })); verification.hidden = false; modal.querySelector('#resendCode').hidden = false; modal.querySelector('#customerAuthSubmit').textContent = 'Confirmar correo ↗'; modal.querySelector('#customerAuthMessage').textContent = `Código enviado a ${email}. En esta demo local: ${code}`; return; } if (stored?.verified && stored.password === password) { saveCustomer({ name: stored.name, email, verified: true }); closeCustomerAuth(modal); updateCustomerUI(); } else if (stored && !stored.verified) modal.querySelector('#customerAuthMessage').textContent = 'Primero verifica tu correo.'; else modal.querySelector('#customerAuthMessage').textContent = 'No encontramos esa cuenta o contraseña.'; });
  modal.querySelector('#resendCode').addEventListener('click', () => { const pending = JSON.parse(localStorage.getItem(pendingKey) || 'null'); if (pending) { pending.code = String(Math.floor(100000 + Math.random() * 900000)); localStorage.setItem(pendingKey, JSON.stringify(pending)); modal.querySelector('#customerAuthMessage').textContent = `Nuevo código enviado a ${pending.email}. En esta demo local: ${pending.code}`; } }); return modal;
}
function openCustomerAuth() { const modal = customerModal(); modal.classList.add('open'); modal.style.opacity = '1'; modal.style.pointerEvents = 'auto'; }
function updateCustomerUI() { const customer = getCustomer(); document.querySelectorAll('[data-customer-name]').forEach((node) => { node.textContent = customer ? customer.name : 'Iniciar sesión'; }); document.querySelectorAll('[data-customer-action]').forEach((node) => node.onclick = customer ? () => { localStorage.removeItem(customerKey); updateCustomerUI(); } : openCustomerAuth); }
function addGlobalCart() { if (document.querySelector('.global-cart-button')) return; const button = document.createElement('a'); button.className = 'global-cart-button'; button.href = 'checkout.html'; button.innerHTML = 'carrito <b id="globalCartCount">0</b>'; document.body.append(button); const update = () => { const count = JSON.parse(localStorage.getItem('ivbags-cart') || '[]').reduce((sum, item) => sum + (item.quantity || 1), 0); button.querySelector('b').textContent = count; }; update(); window.addEventListener('storage', update); }
document.addEventListener('DOMContentLoaded', () => { customerModal(); updateCustomerUI(); addGlobalCart(); });
