const cartStoreKey = 'ivbags-cart';
function getCart() { return JSON.parse(localStorage.getItem(cartStoreKey) || '[]'); }
function addStoreItem(item) { const cart = getCart(); cart.push({ id: `${item.name}-${Date.now()}`, quantity: 1, ...item }); localStorage.setItem(cartStoreKey, JSON.stringify(cart)); window.dispatchEvent(new Event('ivbags-cart-updated')); showStoreToast(`${item.name} está en tu carrito`); }
function showStoreToast(message) { let toast = document.querySelector('.store-toast'); if (!toast) { toast = document.createElement('div'); toast.className = 'store-toast'; document.body.append(toast); } toast.textContent = message; toast.classList.add('visible'); setTimeout(() => toast.classList.remove('visible'), 2200); }
function productDetail(product) {
  let modal = document.querySelector('#productDetailModal'); if (!modal) { modal = document.createElement('div'); modal.id = 'productDetailModal'; modal.className = 'product-detail-modal'; document.body.append(modal); }
  const storedGallery = typeof product.image_urls === 'string' ? JSON.parse(product.image_urls || '[]') : product.image_urls;
  const gallery = Array.isArray(storedGallery) && storedGallery.length ? storedGallery : (product.image_url ? [product.image_url] : []);
  let current = 0;
  const renderImage = () => { const image = modal.querySelector('.product-detail-gallery img'); const counter = modal.querySelector('.product-detail-gallery-count'); if (image && gallery.length) { image.src = gallery[current]; image.alt = `${product.name} imagen ${current + 1}`; } if (counter) counter.textContent = `${current + 1} / ${gallery.length || 1}`; };
  modal.innerHTML = `<div class="product-detail-card"><button class="product-detail-close" type="button" aria-label="Cerrar">×</button><div class="product-detail-media">${gallery.length ? `<div class="product-detail-gallery"><button class="gallery-arrow gallery-prev" type="button" aria-label="Imagen anterior">‹</button><img src="${gallery[0]}" alt="${product.name}"/><button class="gallery-arrow gallery-next" type="button" aria-label="Siguiente imagen">›</button><span class="product-detail-gallery-count">1 / ${gallery.length}</span></div>` : '<span>✦</span>'}</div><div class="product-detail-copy"><small class="product-category-tag">${product.category}</small><h2>${product.name}</h2><p class="product-detail-type">${product.is_customized ? 'pieza personalizable' : 'pieza terminada a mano'}</p><p>Una pieza hecha con calma, materiales seleccionados y atención a cada detalle. Consulta disponibilidad y agrega esta pieza a tu carrito.</p><strong class="product-detail-price">$${Number(product.price).toLocaleString('es-CO')}</strong><span class="product-detail-stock">${Number(product.stock) > 0 ? `${product.stock} disponibles` : 'Agotado'}</span><button class="page-action product-detail-add" type="button" ${Number(product.stock) < 1 ? 'disabled' : ''}>Añadir al carrito ↗</button></div></div>`;
  modal.classList.add('open'); modal.querySelector('.product-detail-close').onclick = () => modal.classList.remove('open'); modal.onclick = (event) => { if (event.target === modal) modal.classList.remove('open'); }; modal.querySelector('.gallery-prev')?.addEventListener('click', () => { current = (current - 1 + gallery.length) % gallery.length; renderImage(); }); modal.querySelector('.gallery-next')?.addEventListener('click', () => { current = (current + 1) % gallery.length; renderImage(); }); modal.querySelector('.product-detail-add')?.addEventListener('click', () => { if (!getCustomer()) { openCustomerAuth(); return; } addStoreItem({ productId: product.id, name: product.name, price: product.price, image: gallery[current] || '', text: product.is_customized ? 'pieza personalizable' : 'pieza terminada a mano' }); modal.classList.remove('open'); });
}
document.addEventListener('DOMContentLoaded', async () => { const grid = document.querySelector('.category-grid'); if (!grid) return; try { const products = await fetch('/api/products').then((response) => response.json()); grid.innerHTML = products.length ? products.map((product, index) => `<article class="category-card" data-product-index="${index}" tabindex="0"><div class="category-art">${product.image_url ? `<img src="${product.image_url}" alt="${product.name}"/>` : `✦<br><br>${product.category}`}</div><div class="category-info"><div><small class="product-category-tag">${product.category}</small><h2>${product.name}</h2><p>${product.is_customized ? 'personalizable' : 'pieza terminada'}</p></div><strong>$${Number(product.price).toLocaleString('es-CO')}</strong></div></article>`).join('') : '<p class="empty-catalog">Todavía no hay piezas publicadas.</p>'; grid.querySelectorAll('.category-card').forEach((card, index) => { card.addEventListener('click', () => productDetail(products[index])); card.addEventListener('keydown', (event) => { if (event.key === 'Enter') productDetail(products[index]); }); }); } catch { grid.innerHTML = '<p class="empty-catalog">No se pudo cargar el catálogo.</p>'; } });
