const customerKey = 'ivbags-customer';
const apiBase = window.IVBAGS_API_URL || (location.hostname === 'localhost' || location.protocol === 'file:' ? 'http://localhost:8787/api' : '/api');
const getCustomer = () => JSON.parse(localStorage.getItem(customerKey) || 'null');
const saveCustomer = (customer) => localStorage.setItem(customerKey, JSON.stringify(customer));
let turnstileReady;
function loadTurnstile() { if (turnstileReady) return turnstileReady; turnstileReady = new Promise((resolve, reject) => { if (window.turnstile) return resolve(); const script = document.createElement('script'); script.src = 'https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit'; script.onload = resolve; script.onerror = () => reject(new Error('No se pudo cargar el captcha de Cloudflare.')); document.head.append(script); }); return turnstileReady; }
function closeCustomerAuth(modal) { modal.classList.remove('open'); modal.style.opacity = '0'; modal.style.pointerEvents = 'none'; }
async function api(path, options = {}) { const controller = new AbortController(); const timeout = setTimeout(() => controller.abort(), 15000); try { const response = await fetch(`${apiBase}${path}`, { ...options, signal: controller.signal, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || `La API respondió con ${response.status}. Comprueba el despliegue de Cloudflare.`); return body; } catch (error) { if (error.name === 'AbortError') throw new Error('La API tardó demasiado en responder. Revisa Cloudflare, D1, KV y Resend.'); if (error instanceof TypeError) throw new Error(`No se pudo conectar con la API (${apiBase}). Comprueba el despliegue de Cloudflare Pages.`); throw error; } finally { clearTimeout(timeout); } }
function customerModal() {
  if (document.querySelector('#customerAuth')) return document.querySelector('#customerAuth');
  const modal = document.createElement('div'); modal.id = 'customerAuth'; modal.className = 'customer-auth';
  modal.innerHTML = `<div class="customer-auth-card"><button class="customer-auth-close" aria-label="Cerrar">×</button><p class="page-kicker">tu espacio iv bags</p><h2>Guarda tus ideas,<br/><em>llévalas contigo.</em></h2><div class="auth-tabs"><button class="active" data-auth-tab="login">Iniciar sesión</button><button data-auth-tab="register">Crear cuenta</button></div><form id="customerAuthForm"><label id="fullNameField" hidden>Nombre<input id="customerFullName" placeholder="Tu nombre"/></label><label>Correo electrónico<input id="customerEmail" type="email" required placeholder="hola@ejemplo.com"/></label><label>WhatsApp<input id="customerPhone" placeholder="300 000 0000"/></label><label>Contraseña<input id="customerPassword" type="password" minlength="8" required pattern="(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^A-Za-z0-9]).{8,}" title="Usa mínimo 8 caracteres, una mayúscula, una minúscula, un número y un símbolo." placeholder="mínimo 8 caracteres"/></label><div id="turnstileWidget" hidden></div><label id="verificationField" hidden>Código recibido por correo<input id="verificationCode" inputmode="numeric" maxlength="6" placeholder="000000"/></label><button class="page-action" type="submit" id="customerAuthSubmit">Entrar a mi espacio ↗</button><button class="resend-code" type="button" id="resendCode" hidden>Solicitar otro código</button><p class="customer-auth-message" id="customerAuthMessage"></p></form><small>Antes de producir tu pieza te contactaremos al WhatsApp registrado.</small></div></div>`;
  document.body.append(modal); let mode = 'login'; let verificationEmail = ''; let verificationMode = false; let turnstileToken = ''; let turnstileWidgetId = null;
  const showVerification = (email, message) => { verificationEmail = email; verificationMode = true; modal.querySelector('#fullNameField').hidden = true; modal.querySelector('#verificationField').hidden = false; modal.querySelector('#resendCode').hidden = false; modal.querySelector('#customerAuthSubmit').textContent = 'Confirmar correo ↗'; modal.querySelector('#customerAuthMessage').textContent = message; renderCaptcha?.(); };
  const setMode = (nextMode) => { mode = nextMode; verificationMode = false; modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.classList.toggle('active', tab.dataset.authTab === mode)); modal.querySelector('#fullNameField').hidden = mode !== 'register'; modal.querySelector('#verificationField').hidden = true; modal.querySelector('#resendCode').hidden = true; modal.querySelector('#customerAuthSubmit').textContent = mode === 'register' ? 'Crear cuenta y enviar código ↗' : 'Entrar a mi espacio ↗'; modal.querySelector('#customerAuthMessage').textContent = ''; };
  const renderCaptcha = async () => { const siteKey = window.IVBAGS_TURNSTILE_SITE_KEY; const widget = modal.querySelector('#turnstileWidget'); if (!siteKey || mode !== 'login' || verificationMode) { widget.hidden = true; return; } widget.hidden = false; try { await loadTurnstile(); if (!widget.dataset.rendered) { turnstileWidgetId = window.turnstile.render(widget, { sitekey: siteKey, action: 'login', callback: (token) => { turnstileToken = token; }, 'expired-callback': () => { turnstileToken = ''; } }); widget.dataset.rendered = 'true'; } } catch (error) { modal.querySelector('#customerAuthMessage').textContent = error.message; } };
  modal.querySelectorAll('[data-auth-tab]').forEach((tab) => tab.addEventListener('click', () => { setMode(tab.dataset.authTab); renderCaptcha(); })); modal.querySelector('.customer-auth-close').addEventListener('click', () => closeCustomerAuth(modal)); modal.addEventListener('click', (event) => { if (event.target === modal) closeCustomerAuth(modal); }); setMode('login'); renderCaptcha();
  modal.querySelector('#customerAuthForm').addEventListener('submit', async (event) => { event.preventDefault(); const message = modal.querySelector('#customerAuthMessage'); const submit = modal.querySelector('#customerAuthSubmit'); submit.disabled = true; message.textContent = 'Conectando con iv bags…'; try { const email = modal.querySelector('#customerEmail').value.trim().toLowerCase(); const password = modal.querySelector('#customerPassword').value; if ((mode === 'register' || verificationMode) && !modal.querySelector('#verificationField').hidden) { const result = await api('/auth/verify', { method: 'POST', body: JSON.stringify({ email: verificationEmail, code: modal.querySelector('#verificationCode').value.trim() }) }); saveCustomer({ ...result.user, token: result.token, verified: true }); closeCustomerAuth(modal); updateCustomerUI(); return; } if (mode === 'register') { const result = await api('/auth/register', { method: 'POST', body: JSON.stringify({ name: modal.querySelector('#customerFullName').value.trim(), email, password, phone: modal.querySelector('#customerPhone').value.trim() }) }); showVerification(email, result.warning ? `${result.message} ${result.warning}` : result.message); return; } const result = await api('/auth/login', { method: 'POST', body: JSON.stringify({ email, password, turnstileToken }) }); saveCustomer({ ...result.user, token: result.token, verified: true }); closeCustomerAuth(modal); updateCustomerUI(); } catch (error) { if (error.message === 'Verifica tu correo antes de entrar') showVerification(email, 'Verifica tu correo electrónico para entrar. Te enviaremos un código nuevo.'); else message.textContent = error.message; } finally { if (turnstileWidgetId !== null && window.turnstile) window.turnstile.reset(turnstileWidgetId); turnstileToken = ''; submit.disabled = false; } });
  modal.querySelector('#resendCode').addEventListener('click', async () => { const resend = modal.querySelector('#resendCode'); const message = modal.querySelector('#customerAuthMessage'); resend.disabled = true; message.textContent = 'Enviando un código nuevo…'; try { const result = await api('/auth/resend', { method: 'POST', body: JSON.stringify({ email: verificationEmail || modal.querySelector('#customerEmail').value.trim().toLowerCase() }) }); showVerification(verificationEmail, result.message); } catch (error) { message.textContent = error.message; } finally { resend.disabled = false; } }); return modal;
}
function openCustomerAuth() { const modal = customerModal(); modal.classList.add('open'); modal.style.opacity = '1'; modal.style.pointerEvents = 'auto'; }
function updateCustomerUI() { const customer = getCustomer(); document.querySelectorAll('[data-customer-name]').forEach((node) => { node.textContent = customer ? customer.name : 'Iniciar sesión'; }); document.querySelectorAll('[data-customer-action]').forEach((node) => node.onclick = customer ? () => { localStorage.removeItem(customerKey); updateCustomerUI(); } : openCustomerAuth); }
function addGlobalCart() { if (document.querySelector('.global-cart-button')) return; const button = document.createElement('a'); button.className = 'global-cart-button'; button.href = 'checkout.html'; button.setAttribute('aria-label', 'Abrir carrito de compras'); button.innerHTML = '<span class="cart-icon" aria-hidden="true"><svg viewBox="0 0 24 24" focusable="false"><path d="M3 4h2l2.2 10.2a2 2 0 0 0 2 1.6h7.9a2 2 0 0 0 1.9-1.4L21 8H6"/><circle cx="10" cy="19" r="1.4"/><circle cx="18" cy="19" r="1.4"/></svg></span><b id="globalCartCount" aria-label="Productos en el carrito">0</b>'; document.body.append(button); const update = () => { const count = JSON.parse(localStorage.getItem('ivbags-cart') || '[]').reduce((sum, item) => sum + (item.quantity || 1), 0); button.querySelector('b').textContent = count; }; update(); window.addEventListener('storage', update); window.addEventListener('ivbags-cart-updated', update); }
document.addEventListener('DOMContentLoaded', () => { customerModal(); updateCustomerUI(); addGlobalCart(); });
